### ISSUE TITLE
Issue with updating to latest sbt version

### ISSUE THREAD

**Issue by morazow** [exasol/cloud-storage-extension#154]
## Situation

Updating to latest sbt version fails with an exception when running tests.

```
[info] Run completed in 2 minutes, 23 seconds.
[info] Total number of tests run: 169
[info] Suites: completed 36, aborted 0
[info] Tests: succeeded 169, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 190 s (03:10), completed Jun 15, 2021, 11:52:24 AM
sbt appears to be exiting abnormally.
  The log file for this session is at /mnt/devel/git/EXASOL/releases/release/cloud-storage-extension/target/global-logging/sbt-global-log14788932046163710743.log
java.lang.ClassCastException: class java.util.concurrent.TimeoutException cannot be cast to class xsbti.FullReload (java.util.concurrent.TimeoutException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.ClassCastException: class java.util.concurrent.TimeoutException cannot be cast to class xsbti.FullReload (java.util.concurrent.TimeoutException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
```

## Acceptance Criteria

- Issue is resolved
- Sbt is updated to latest version

**Comment by morazow** [comment]
Fixed in #158.
